In [1]:
import numpy as np

1. Matrix Operation

In [9]:
A=np.array([[2,-1],[0,3]])
B=np.array([[1,2],[-3,4]])
add=A+B
mul=np.dot(A,B)
l= 3*A-2*B
print("A+B=\n",add)
print("\nAB=\n",mul)
print("\n3A-2B=\n",l)

A+B=
 [[ 3  1]
 [-3  7]]

AB=
 [[ 5  0]
 [-9 12]]

3A-2B=
 [[ 4 -7]
 [ 6  1]]


2. Determinants and Inverses  

In [13]:
A=np.array([[2,-1],[0,3]])
d=np.linalg.det(A)
print("Determinant:", d)
if d!=0:
    print("Inverse:")
    print(np.linalg.inv(A))
else:
    print("Inverse does not exist")

Determinant: 6.0
Inverse:
[[0.5        0.16666667]
 [0.         0.33333333]]


3. Eigenvalues and Eigenvectors  

In [22]:
C=np.array([[4,1],[-2,1]])
eigenvalues, eigenvectors = np.linalg.eig(C)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [3. 2.]
Eigenvectors:
 [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


4. You are given a dataset of cars with the following features:Number of cylinders (x1​)Engine size in liters (x2​)Horsepower (x3)

In [20]:
X=np.array([[4,1.5,100],[6,2.0,150]])
y=np.array([20,30])
car3=np.array([8,3.0,200])
c=np.dot(np.linalg.pinv(X),y)
pcar3 = np.dot(car3,c)
print("Coefficient vector:")
print(c)
print("\nPredicted price of car 3:")
print(pcar3)

Coefficient vector:
[7.98722045e-03 2.84217094e-14 1.99680511e-01]

Predicted price of car 3:
40.00000000000002
